spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/clinicaldb
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        # dialect: org.hibernate.dialect.PostgreSQLDialect
        # format_sql: true
        transaction:
          jta:
            platform: org.hibernate.service.jta.platform.internal.NoJtaPlatform
    open-in-view: false
  sql:
    init:
      mode: always
application:
  cors:
    allowed-origins: http://localhost:3000,http://54.211.242.156:8088,http://54.211.242.156:8080
server:
  port: 8088
